import { ImageSourcePropType } from 'react-native';
import { API_URL } from '@/constants/config';

/**
 * The six official TicketFlow Kenya event posters, bundled into the app.
 *
 * These are the same artwork files the web app serves from `/posters/*.jpg`
 * (generated by `frontend/scripts/generate-posters.py`). Bundling them means
 * the catalogue renders instantly and works with no network at all — the
 * remote copies live on a free Render instance that sleeps when idle, so
 * relying on those URLs left every card showing a grey placeholder.
 */
const BUNDLED_POSTERS: Record<string, ImageSourcePropType> = {
  'august-nights-afro-fusion-live.jpg': require('../../assets/posters/august-nights-afro-fusion-live.jpg'),
  'coast-sevens-rugby-festival.jpg': require('../../assets/posters/coast-sevens-rugby-festival.jpg'),
  'nairobi-coffee-culture-festival.jpg': require('../../assets/posters/nairobi-coffee-culture-festival.jpg'),
  'nairobi-fintech-ai-summit-2026.jpg': require('../../assets/posters/nairobi-fintech-ai-summit-2026.jpg'),
  'sanaa-live-spoken-word-theatre-night.jpg': require('../../assets/posters/sanaa-live-spoken-word-theatre-night.jpg'),
  'watamu-ocean-seafood-festival.jpg': require('../../assets/posters/watamu-ocean-seafood-festival.jpg'),
};

/** Origin of the backend host (API_URL minus the trailing `/api` path). */
function backendOrigin(): string | undefined {
  if (!API_URL) return undefined;
  try {
    return new URL(API_URL).origin;
  } catch {
    return undefined;
  }
}

/**
 * Turns whatever `posterUrl` we were given into something `<Image>` can render.
 *
 * Handles all three shapes the app sees:
 *  - `/posters/<name>.jpg` — what the real backend stores. Served by the *web*
 *    app, not the API, so a bundled copy is preferred; otherwise resolved
 *    against the backend origin.
 *  - `https://…` — an absolute URL (organizer-uploaded posters) → used as-is.
 *  - anything unrecognised → `undefined`, so callers can fall back to a
 *    placeholder instead of rendering a broken image.
 */
export function resolvePosterSource(posterUrl?: string | null): ImageSourcePropType | undefined {
  if (!posterUrl) return undefined;

  const fileName = posterUrl.split('/').pop() ?? '';
  const bundled = BUNDLED_POSTERS[fileName];
  if (bundled) return bundled;

  if (/^https?:\/\//i.test(posterUrl)) return { uri: posterUrl };

  if (posterUrl.startsWith('/')) {
    const origin = backendOrigin();
    return origin ? { uri: `${origin}${posterUrl}` } : undefined;
  }

  return undefined;
}
