import { EventItem } from '@/types';

const category = (id: string, name: string, slug: string) => ({ id, name, slug });
const ticket = (eventId: string, name: string, price: number) => ({
  id: eventId + '-ticket',
  eventId,
  name,
  category: 'REGULAR' as const,
  price,
  quantity: 10000,
  quantitySold: 0,
  availabilityStatus: 'AVAILABLE' as const,
});

export const CURATED_EVENTS: EventItem[] = [
  {
    id: 'calendar-miles-of-melody',
    slug: 'miles-of-melody-where-rhythm-roams-2026',
    title: 'Miles of Melody: Where Rhythm Roams',
    subtitle: 'The Catalog 254 — music, conversation and community',
    description: 'An intimate afternoon built around music, conversation and community, with the featured artist in the room to unpack the creative process track by track.',
    posterUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=88',
    posterAlt: 'Live singer performing under warm stage lights',
    venue: 'Chronos',
    city: 'Nairobi',
    county: 'Nairobi',
    address: 'Lavington, Nairobi',
    organizerName: 'The Catalog 254',
    startDateTime: '2026-09-26T15:00:00+03:00',
    endDateTime: '2026-09-26T21:00:00+03:00',
    status: 'PUBLISHED',
    isFeatured: true,
    bookingMode: 'EXTERNAL',
    bookingUrl: 'https://www.tikohub.com/events/miles-of-melody-where-rhythm-roams',
    verificationSource: 'TikoHUB',
    verificationSourceUrl: 'https://www.tikohub.com/events/miles-of-melody-where-rhythm-roams',
    verifiedAt: '2026-09-25T19:00:00+03:00',
    salesEnabled: false,
    isDemo: false,
    isBookable: false,
    category: category('calendar-entertainment', 'Entertainment', 'entertainment'),
    ticketTypes: [ticket('calendar-miles-of-melody', 'Entry ticket', 1000)],
  },
  {
    id: 'calendar-concours-2026',
    slug: 'africa-concours-delegance-2026',
    title: 'Africa Concours d’Elegance 2026',
    subtitle: 'Vintage cars, classic motorcycles and Kenya motoring culture',
    description: 'Kenya’s long-running classic motoring showcase returns to Ngong Racecourse with vintage and classic cars, motorcycles and a full day of automotive culture.',
    posterUrl: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=88',
    posterAlt: 'Classic sports car displayed outdoors',
    venue: 'Ngong Racecourse',
    city: 'Nairobi',
    county: 'Nairobi',
    address: 'Ngong Road, Nairobi',
    organizerName: 'Africa Concours d’Elegance',
    startDateTime: '2026-09-27T09:00:00+03:00',
    endDateTime: '2026-09-27T18:00:00+03:00',
    status: 'PUBLISHED',
    isFeatured: true,
    bookingMode: 'EXTERNAL',
    bookingUrl: 'https://apps.little.africa/events/55',
    verificationSource: 'Little Events',
    verificationSourceUrl: 'https://apps.little.africa/events/55',
    secondaryVerificationSourceUrl: 'https://nairobieventsguide.com/event/2026-africa-concours-delegance/',
    verifiedAt: '2026-09-25T19:00:00+03:00',
    salesEnabled: false,
    isDemo: false,
    isBookable: false,
    category: category('calendar-motoring', 'Motoring', 'motoring'),
    ticketTypes: [ticket('calendar-concours-2026', 'Advance adult', 1800)],
  },
  {
    id: 'calendar-rhumba-vip',
    slug: 'first-rhumba-vip-affair-2026',
    title: 'The First Rhumba VIP Affair',
    subtitle: 'A premium live Rhumba night at Emara Ole-Sereni',
    description: 'A premium Rhumba experience bringing together live bands, DJs, hospitality and an elegant evening atmosphere at Emara Ole-Sereni.',
    posterUrl: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=88',
    posterAlt: 'Musician performing live on stage',
    venue: 'Emara Ole-Sereni',
    city: 'Nairobi',
    county: 'Nairobi',
    address: 'Mombasa Road, Nairobi',
    organizerName: 'Zeget Delongeur & E&F Sounds Entertainment',
    startDateTime: '2026-10-03T18:00:00+03:00',
    endDateTime: '2026-10-04T02:00:00+03:00',
    status: 'PUBLISHED',
    isFeatured: true,
    bookingMode: 'EXTERNAL',
    bookingUrl: 'https://tikohub.com/events/the-first-rhumba-vip-affair',
    verificationSource: 'TikoHUB',
    verificationSourceUrl: 'https://tikohub.com/events/the-first-rhumba-vip-affair',
    verifiedAt: '2026-09-25T19:00:00+03:00',
    salesEnabled: false,
    isDemo: false,
    isBookable: false,
    category: category('calendar-music', 'Music', 'music'),
    ticketTypes: [ticket('calendar-rhumba-vip', 'VIP ticket', 3000)],
  },
  {
    id: 'calendar-safari-7s',
    slug: 'safari-7s-2026',
    title: 'Safari 7s 2026',
    subtitle: 'Three days of rugby, entertainment and festival energy',
    description: 'East Africa’s rugby festival returns to Nyayo Stadium for three days of sevens rugby, entertainment and a high-energy stadium atmosphere.',
    posterUrl: 'https://images.unsplash.com/photo-1515808266237-4f89cbe46c1c?auto=format&fit=crop&w=1200&q=88',
    posterAlt: 'Rugby players competing on a green field',
    venue: 'Nyayo Stadium',
    city: 'Nairobi',
    county: 'Nairobi',
    address: 'Nyayo National Stadium, Nairobi',
    organizerName: 'Safari 7s',
    startDateTime: '2026-10-09T07:30:00+03:00',
    endDateTime: '2026-10-11T20:00:00+03:00',
    status: 'PUBLISHED',
    isFeatured: true,
    bookingMode: 'EXTERNAL',
    bookingUrl: 'https://tikohub.com/events/safari-7s-2026',
    verificationSource: 'TikoHUB',
    verificationSourceUrl: 'https://tikohub.com/events/safari-7s-2026',
    verifiedAt: '2026-09-25T19:00:00+03:00',
    salesEnabled: false,
    isDemo: false,
    isBookable: false,
    category: category('calendar-sports', 'Sports', 'sports'),
    ticketTypes: [ticket('calendar-safari-7s', 'Friday regular', 300)],
  },
  {
    id: 'calendar-kulture-2026',
    slug: 'kulture-icons-soundtrack-2026',
    title: 'KULTURE: Celebrating the Icons & The Soundtrack',
    subtitle: 'A seated celebration of the music that shaped a generation',
    description: 'An evening celebrating influential music and cultural icons, with red carpet arrivals followed by a gala show at the Tsavo Ballroom, KICC.',
    posterUrl: 'https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1200&q=88',
    posterAlt: 'Audience watching a theatrical stage performance',
    venue: 'Tsavo Ballroom, KICC',
    city: 'Nairobi',
    county: 'Nairobi',
    address: 'Kenyatta International Convention Centre, Nairobi',
    organizerName: 'KULTURE',
    startDateTime: '2026-10-10T16:00:00+03:00',
    endDateTime: '2026-10-11T00:00:00+03:00',
    status: 'PUBLISHED',
    isFeatured: true,
    bookingMode: 'EXTERNAL',
    bookingUrl: 'https://kulture.ke/tickets',
    verificationSource: 'KULTURE',
    verificationSourceUrl: 'https://kulture.ke/',
    verifiedAt: '2026-09-25T19:00:00+03:00',
    salesEnabled: false,
    isDemo: false,
    isBookable: false,
    category: category('calendar-culture', 'Culture', 'culture'),
    ticketTypes: [ticket('calendar-kulture-2026', 'Zone H', 2000)],
  },
  {
    id: 'calendar-pineapple-party',
    slug: 'pineapple-party-nairobi-2026',
    title: 'Pineapple Party',
    subtitle: 'A Saturday music and nightlife experience in Westlands',
    description: 'A Nairobi weekend party experience at Nairobi Street Kitchen, bringing together music, food and a lively social crowd.',
    posterUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=88',
    posterAlt: 'Crowd enjoying a colourful outdoor music event',
    venue: 'Nairobi Street Kitchen',
    city: 'Nairobi',
    county: 'Nairobi',
    address: 'Mpaka Road, Westlands, Nairobi',
    organizerName: 'Pineapple Party',
    startDateTime: '2026-10-10T16:00:00+03:00',
    endDateTime: '2026-10-11T02:00:00+03:00',
    status: 'PUBLISHED',
    isFeatured: false,
    bookingMode: 'EXTERNAL',
    bookingUrl: 'https://www.tipsitickets.com/',
    verificationSource: 'Tipsi Tickets',
    verificationSourceUrl: 'https://www.tipsitickets.com/',
    verifiedAt: '2026-09-25T19:00:00+03:00',
    salesEnabled: false,
    isDemo: false,
    isBookable: false,
    category: category('calendar-nightlife', 'Nightlife', 'nightlife'),
    ticketTypes: [ticket('calendar-pineapple-party', 'Entry', 1500)],
  },
  {
    id: 'calendar-midnight-royale',
    slug: 'midnight-royale-2026',
    title: 'Midnight Royale',
    subtitle: 'A late-night Nairobi experience at Carnivore Grounds',
    description: 'A Saturday-to-Sunday entertainment experience at The Carnivore Grounds, with tickets listed from KES 1,500.',
    posterUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=88',
    posterAlt: 'Large concert crowd under red stage lighting',
    venue: 'The Carnivore Grounds',
    city: 'Nairobi',
    county: 'Nairobi',
    address: 'Langata Road, Nairobi',
    organizerName: 'Midnight Royale',
    startDateTime: '2026-10-17T15:00:00+03:00',
    endDateTime: '2026-10-18T03:00:00+03:00',
    status: 'PUBLISHED',
    isFeatured: false,
    bookingMode: 'EXTERNAL',
    bookingUrl: 'https://www.tipsitickets.com/',
    verificationSource: 'Tipsi Tickets',
    verificationSourceUrl: 'https://www.tipsitickets.com/',
    verifiedAt: '2026-09-25T19:00:00+03:00',
    salesEnabled: false,
    isDemo: false,
    isBookable: false,
    category: category('calendar-entertainment-2', 'Entertainment', 'entertainment'),
    ticketTypes: [ticket('calendar-midnight-royale', 'Entry', 1500)],
  },
  {
    id: 'calendar-teen-popup',
    slug: 'teen-pop-up-festival-2026',
    title: '2nd Edition Teen Pop Up Festival',
    subtitle: 'A daytime youth festival at Nairobi Arboretum',
    description: 'A daytime festival at Nairobi Arboretum with affordable entry and a youth-focused mix of social, creative and entertainment experiences.',
    posterUrl: 'https://images.unsplash.com/photo-1496024840928-4c417adf211d?auto=format&fit=crop&w=1200&q=88',
    posterAlt: 'Outdoor festival crowd in daylight',
    venue: 'The Nairobi Arboretum',
    city: 'Nairobi',
    county: 'Nairobi',
    address: 'State House Road, Nairobi',
    organizerName: 'Teen Pop Up Festival',
    startDateTime: '2026-10-24T06:00:00+03:00',
    endDateTime: '2026-10-24T16:00:00+03:00',
    status: 'PUBLISHED',
    isFeatured: false,
    bookingMode: 'EXTERNAL',
    bookingUrl: 'https://www.tipsitickets.com/',
    verificationSource: 'Tipsi Tickets',
    verificationSourceUrl: 'https://www.tipsitickets.com/',
    verifiedAt: '2026-09-25T19:00:00+03:00',
    salesEnabled: false,
    isDemo: false,
    isBookable: false,
    category: category('calendar-festival', 'Festival', 'festival'),
    ticketTypes: [ticket('calendar-teen-popup', 'Entry', 250)],
  },
  {
    id: 'calendar-ai-build-day',
    slug: 'ai-build-day-2nd-edition-2026',
    title: 'AI Build Day — 2nd Edition',
    subtitle: 'A technology build day at Strathmore University',
    description: 'A hands-on technology event at Strathmore University for builders, developers and people interested in creating with AI.',
    posterUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=88',
    posterAlt: 'Developer working on code at a laptop',
    venue: 'Strathmore University',
    city: 'Nairobi',
    county: 'Nairobi',
    address: 'Madaraka Estate, Nairobi',
    organizerName: 'AI Build Day',
    startDateTime: '2026-11-06T06:00:00+03:00',
    endDateTime: '2026-11-06T14:00:00+03:00',
    status: 'PUBLISHED',
    isFeatured: false,
    bookingMode: 'EXTERNAL',
    bookingUrl: 'https://www.tipsitickets.com/',
    verificationSource: 'Tipsi Tickets',
    verificationSourceUrl: 'https://www.tipsitickets.com/',
    verifiedAt: '2026-09-25T19:00:00+03:00',
    salesEnabled: false,
    isDemo: false,
    isBookable: false,
    category: category('calendar-tech', 'Technology', 'technology'),
    ticketTypes: [ticket('calendar-ai-build-day', 'Entry', 800)],
  },
];

export function getCuratedEvent(idOrSlug: string) {
  return CURATED_EVENTS.find((event) => event.id === idOrSlug || event.slug === idOrSlug) || null;
}

export function getCuratedUpcoming(reference = new Date()) {
  return CURATED_EVENTS
    .filter((event) => new Date(event.endDateTime).getTime() >= reference.getTime())
    .sort((a, b) => Date.parse(a.startDateTime) - Date.parse(b.startDateTime));
}
